spring:
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  datasource:
    url: jdbc:h2:tcp://localhost/~/jpapost
    username: jpa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.Type: trace

